// 通貨マスタデータ
// code: ISO4217通貨コード / nameJa: 日本語名 / nameEn: 英語名 / iso2: 国旗表示用の国コード(flagcdn.com用)
const CURRENCIES = [
  { code: "JPY", nameJa: "日本円", nameEn: "Japanese Yen", iso2: "jp" },
  { code: "AED", nameJa: "UAEディルハム", nameEn: "UAE Dirham", iso2: "ae" },
  { code: "AFN", nameJa: "アフガニ", nameEn: "Afghan Afghani", iso2: "af" },
  { code: "ALL", nameJa: "レク", nameEn: "Albanian Lek", iso2: "al" },
  { code: "AMD", nameJa: "ドラム", nameEn: "Armenian Dram", iso2: "am" },
  { code: "ANG", nameJa: "アンティル・ギルダー", nameEn: "Netherlands Antillean Guilder", iso2: "cw" },
  { code: "AOA", nameJa: "クワンザ", nameEn: "Angolan Kwanza", iso2: "ao" },
  { code: "ARS", nameJa: "アルゼンチン・ペソ", nameEn: "Argentine Peso", iso2: "ar" },
  { code: "AUD", nameJa: "オーストラリアドル", nameEn: "Australian Dollar", iso2: "au" },
  { code: "AWG", nameJa: "アルバ・フロリン", nameEn: "Aruban Florin", iso2: "aw" },
  { code: "AZN", nameJa: "マナト", nameEn: "Azerbaijani Manat", iso2: "az" },
  { code: "BAM", nameJa: "兌換マルク", nameEn: "Bosnia-Herzegovina Convertible Mark", iso2: "ba" },
  { code: "BBD", nameJa: "バルバドスドル", nameEn: "Barbadian Dollar", iso2: "bb" },
  { code: "BDT", nameJa: "タカ", nameEn: "Bangladeshi Taka", iso2: "bd" },
  { code: "BGN", nameJa: "レフ", nameEn: "Bulgarian Lev", iso2: "bg" },
  { code: "BHD", nameJa: "バーレーン・ディナール", nameEn: "Bahraini Dinar", iso2: "bh" },
  { code: "BIF", nameJa: "ブルンジ・フラン", nameEn: "Burundian Franc", iso2: "bi" },
  { code: "BMD", nameJa: "バミューダドル", nameEn: "Bermudian Dollar", iso2: "bm" },
  { code: "BND", nameJa: "ブルネイドル", nameEn: "Brunei Dollar", iso2: "bn" },
  { code: "BOB", nameJa: "ボリビアーノ", nameEn: "Bolivian Boliviano", iso2: "bo" },
  { code: "BRL", nameJa: "ブラジルレアル", nameEn: "Brazilian Real", iso2: "br" },
  { code: "BSD", nameJa: "バハマドル", nameEn: "Bahamian Dollar", iso2: "bs" },
  { code: "BTN", nameJa: "ニュルタム", nameEn: "Bhutanese Ngultrum", iso2: "bt" },
  { code: "BWP", nameJa: "プラ", nameEn: "Botswana Pula", iso2: "bw" },
  { code: "BYN", nameJa: "ベラルーシルーブル", nameEn: "Belarusian Ruble", iso2: "by" },
  { code: "BZD", nameJa: "ベリーズドル", nameEn: "Belize Dollar", iso2: "bz" },
  { code: "CAD", nameJa: "カナダドル", nameEn: "Canadian Dollar", iso2: "ca" },
  { code: "CDF", nameJa: "コンゴ・フラン", nameEn: "Congolese Franc", iso2: "cd" },
  { code: "CHF", nameJa: "スイスフラン", nameEn: "Swiss Franc", iso2: "ch" },
  { code: "CLP", nameJa: "チリペソ", nameEn: "Chilean Peso", iso2: "cl" },
  { code: "CNH", nameJa: "人民元(オフショア)", nameEn: "Offshore Chinese Yuan", iso2: "cn" },
  { code: "CNY", nameJa: "中国人民元", nameEn: "Chinese Yuan Renminbi", iso2: "cn" },
  { code: "COP", nameJa: "コロンビアペソ", nameEn: "Colombian Peso", iso2: "co" },
  { code: "CRC", nameJa: "コスタリカ・コロン", nameEn: "Costa Rican Colón", iso2: "cr" },
  { code: "CUP", nameJa: "キューバペソ", nameEn: "Cuban Peso", iso2: "cu" },
  { code: "CVE", nameJa: "エスクード", nameEn: "Cape Verdean Escudo", iso2: "cv" },
  { code: "CZK", nameJa: "チェココルナ", nameEn: "Czech Koruna", iso2: "cz" },
  { code: "DJF", nameJa: "ジブチフラン", nameEn: "Djiboutian Franc", iso2: "dj" },
  { code: "DKK", nameJa: "デンマーククローネ", nameEn: "Danish Krone", iso2: "dk" },
  { code: "DOP", nameJa: "ドミニカペソ", nameEn: "Dominican Peso", iso2: "do" },
  { code: "DZD", nameJa: "アルジェリアディナール", nameEn: "Algerian Dinar", iso2: "dz" },
  { code: "EGP", nameJa: "エジプトポンド", nameEn: "Egyptian Pound", iso2: "eg" },
  { code: "ERN", nameJa: "ナクファ", nameEn: "Eritrean Nakfa", iso2: "er" },
  { code: "ETB", nameJa: "ブル", nameEn: "Ethiopian Birr", iso2: "et" },
  { code: "EUR", nameJa: "ユーロ", nameEn: "Euro", iso2: "eu" },
  { code: "FJD", nameJa: "フィジードル", nameEn: "Fijian Dollar", iso2: "fj" },
  { code: "FKP", nameJa: "フォークランドポンド", nameEn: "Falkland Islands Pound", iso2: "fk" },
  { code: "GBP", nameJa: "英ポンド", nameEn: "British Pound Sterling", iso2: "gb" },
  { code: "GEL", nameJa: "ラリ", nameEn: "Georgian Lari", iso2: "ge" },
  { code: "GGP", nameJa: "ガーンジーポンド", nameEn: "Guernsey Pound", iso2: "gg" },
  { code: "GHS", nameJa: "セディ", nameEn: "Ghanaian Cedi", iso2: "gh" },
  { code: "GIP", nameJa: "ジブラルタルポンド", nameEn: "Gibraltar Pound", iso2: "gi" },
  { code: "GMD", nameJa: "ダラシ", nameEn: "Gambian Dalasi", iso2: "gm" },
  { code: "GNF", nameJa: "ギニアフラン", nameEn: "Guinean Franc", iso2: "gn" },
  { code: "GTQ", nameJa: "ケツァル", nameEn: "Guatemalan Quetzal", iso2: "gt" },
  { code: "GYD", nameJa: "ガイアナドル", nameEn: "Guyanese Dollar", iso2: "gy" },
  { code: "HKD", nameJa: "香港ドル", nameEn: "Hong Kong Dollar", iso2: "hk" },
  { code: "HNL", nameJa: "レンピラ", nameEn: "Honduran Lempira", iso2: "hn" },
  { code: "HTG", nameJa: "グールド", nameEn: "Haitian Gourde", iso2: "ht" },
  { code: "HUF", nameJa: "フォリント", nameEn: "Hungarian Forint", iso2: "hu" },
  { code: "IDR", nameJa: "ルピア", nameEn: "Indonesian Rupiah", iso2: "id" },
  { code: "ILS", nameJa: "新シェケル", nameEn: "Israeli New Shekel", iso2: "il" },
  { code: "IMP", nameJa: "マン島ポンド", nameEn: "Manx Pound", iso2: "im" },
  { code: "INR", nameJa: "ルピー", nameEn: "Indian Rupee", iso2: "in" },
  { code: "IQD", nameJa: "イラクディナール", nameEn: "Iraqi Dinar", iso2: "iq" },
  { code: "IRR", nameJa: "イラン・リアル", nameEn: "Iranian Rial", iso2: "ir" },
  { code: "ISK", nameJa: "アイスランドクローナ", nameEn: "Icelandic Króna", iso2: "is" },
  { code: "JEP", nameJa: "ジャージーポンド", nameEn: "Jersey Pound", iso2: "je" },
  { code: "JMD", nameJa: "ジャマイカドル", nameEn: "Jamaican Dollar", iso2: "jm" },
  { code: "JOD", nameJa: "ヨルダンディナール", nameEn: "Jordanian Dinar", iso2: "jo" },
  { code: "KES", nameJa: "ケニアシリング", nameEn: "Kenyan Shilling", iso2: "ke" },
  { code: "KGS", nameJa: "ソム", nameEn: "Kyrgyzstani Som", iso2: "kg" },
  { code: "KHR", nameJa: "リエル", nameEn: "Cambodian Riel", iso2: "kh" },
  { code: "KMF", nameJa: "コモロフラン", nameEn: "Comorian Franc", iso2: "km" },
  { code: "KPW", nameJa: "北朝鮮ウォン", nameEn: "North Korean Won", iso2: "kp" },
  { code: "KRW", nameJa: "韓国ウォン", nameEn: "South Korean Won", iso2: "kr" },
  { code: "KWD", nameJa: "クウェートディナール", nameEn: "Kuwaiti Dinar", iso2: "kw" },
  { code: "KYD", nameJa: "ケイマン諸島ドル", nameEn: "Cayman Islands Dollar", iso2: "ky" },
  { code: "KZT", nameJa: "テンゲ", nameEn: "Kazakhstani Tenge", iso2: "kz" },
  { code: "LAK", nameJa: "キープ", nameEn: "Lao Kip", iso2: "la" },
  { code: "LBP", nameJa: "レバノンポンド", nameEn: "Lebanese Pound", iso2: "lb" },
  { code: "LKR", nameJa: "スリランカルピー", nameEn: "Sri Lankan Rupee", iso2: "lk" },
  { code: "LRD", nameJa: "リベリアドル", nameEn: "Liberian Dollar", iso2: "lr" },
  { code: "LSL", nameJa: "ロチ", nameEn: "Lesotho Loti", iso2: "ls" },
  { code: "LYD", nameJa: "リビアディナール", nameEn: "Libyan Dinar", iso2: "ly" },
  { code: "MAD", nameJa: "モロッコディルハム", nameEn: "Moroccan Dirham", iso2: "ma" },
  { code: "MDL", nameJa: "レウ", nameEn: "Moldovan Leu", iso2: "md" },
  { code: "MGA", nameJa: "アリアリ", nameEn: "Malagasy Ariary", iso2: "mg" },
  { code: "MKD", nameJa: "デナール", nameEn: "Macedonian Denar", iso2: "mk" },
  { code: "MMK", nameJa: "チャット", nameEn: "Myanmar Kyat", iso2: "mm" },
  { code: "MNT", nameJa: "トゥグルグ", nameEn: "Mongolian Tögrög", iso2: "mn" },
  { code: "MOP", nameJa: "パタカ", nameEn: "Macanese Pataca", iso2: "mo" },
  { code: "MRU", nameJa: "ウギア", nameEn: "Mauritanian Ouguiya", iso2: "mr" },
  { code: "MUR", nameJa: "モーリシャスルピー", nameEn: "Mauritian Rupee", iso2: "mu" },
  { code: "MVR", nameJa: "ルフィア", nameEn: "Maldivian Rufiyaa", iso2: "mv" },
  { code: "MWK", nameJa: "クワチャ", nameEn: "Malawian Kwacha", iso2: "mw" },
  { code: "MXN", nameJa: "メキシコペソ", nameEn: "Mexican Peso", iso2: "mx" },
  { code: "MYR", nameJa: "リンギット", nameEn: "Malaysian Ringgit", iso2: "my" },
  { code: "MZN", nameJa: "メティカル", nameEn: "Mozambican Metical", iso2: "mz" },
  { code: "NAD", nameJa: "ナミビアドル", nameEn: "Namibian Dollar", iso2: "na" },
  { code: "NGN", nameJa: "ナイラ", nameEn: "Nigerian Naira", iso2: "ng" },
  { code: "NIO", nameJa: "コルドバ", nameEn: "Nicaraguan Córdoba", iso2: "ni" },
  { code: "NOK", nameJa: "ノルウェークローネ", nameEn: "Norwegian Krone", iso2: "no" },
  { code: "NPR", nameJa: "ネパールルピー", nameEn: "Nepalese Rupee", iso2: "np" },
  { code: "NZD", nameJa: "ニュージーランドドル", nameEn: "New Zealand Dollar", iso2: "nz" },
  { code: "OMR", nameJa: "オマーンリアル", nameEn: "Omani Rial", iso2: "om" },
  { code: "PAB", nameJa: "バルボア", nameEn: "Panamanian Balboa", iso2: "pa" },
  { code: "PEN", nameJa: "ソル", nameEn: "Peruvian Sol", iso2: "pe" },
  { code: "PGK", nameJa: "キナ", nameEn: "Papua New Guinean Kina", iso2: "pg" },
  { code: "PHP", nameJa: "フィリピンペソ", nameEn: "Philippine Peso", iso2: "ph" },
  { code: "PKR", nameJa: "パキスタンルピー", nameEn: "Pakistani Rupee", iso2: "pk" },
  { code: "PLN", nameJa: "ズウォティ", nameEn: "Polish Złoty", iso2: "pl" },
  { code: "PYG", nameJa: "グアラニー", nameEn: "Paraguayan Guaraní", iso2: "py" },
  { code: "QAR", nameJa: "カタールリヤル", nameEn: "Qatari Riyal", iso2: "qa" },
  { code: "RON", nameJa: "レウ", nameEn: "Romanian Leu", iso2: "ro" },
  { code: "RSD", nameJa: "ディナール", nameEn: "Serbian Dinar", iso2: "rs" },
  { code: "RUB", nameJa: "ロシアルーブル", nameEn: "Russian Ruble", iso2: "ru" },
  { code: "RWF", nameJa: "ルワンダフラン", nameEn: "Rwandan Franc", iso2: "rw" },
  { code: "SAR", nameJa: "サウジリヤル", nameEn: "Saudi Riyal", iso2: "sa" },
  { code: "SBD", nameJa: "ソロモンドル", nameEn: "Solomon Islands Dollar", iso2: "sb" },
  { code: "SCR", nameJa: "セーシェルルピー", nameEn: "Seychellois Rupee", iso2: "sc" },
  { code: "SDG", nameJa: "スーダンポンド", nameEn: "Sudanese Pound", iso2: "sd" },
  { code: "SEK", nameJa: "スウェーデンクローナ", nameEn: "Swedish Krona", iso2: "se" },
  { code: "SGD", nameJa: "シンガポールドル", nameEn: "Singapore Dollar", iso2: "sg" },
  { code: "SHP", nameJa: "セントヘレナポンド", nameEn: "Saint Helena Pound", iso2: "sh" },
  { code: "SLL", nameJa: "レオン", nameEn: "Sierra Leonean Leone", iso2: "sl" },
  { code: "SOS", nameJa: "ソマリアシリング", nameEn: "Somali Shilling", iso2: "so" },
  { code: "SRD", nameJa: "スリナムドル", nameEn: "Surinamese Dollar", iso2: "sr" },
  { code: "SSP", nameJa: "南スーダンポンド", nameEn: "South Sudanese Pound", iso2: "ss" },
  { code: "STN", nameJa: "新ドブラ", nameEn: "São Tomé and Príncipe Dobra", iso2: "st" },
  { code: "SVC", nameJa: "エルサルバドルコロン", nameEn: "Salvadoran Colón", iso2: "sv" },
  { code: "SYP", nameJa: "シリアポンド", nameEn: "Syrian Pound", iso2: "sy" },
  { code: "SZL", nameJa: "リランゲニ", nameEn: "Swazi Lilangeni", iso2: "sz" },
  { code: "THB", nameJa: "バーツ", nameEn: "Thai Baht", iso2: "th" },
  { code: "TJS", nameJa: "ソモニ", nameEn: "Tajikistani Somoni", iso2: "tj" },
  { code: "TMT", nameJa: "マナト", nameEn: "Turkmenistani Manat", iso2: "tm" },
  { code: "TND", nameJa: "チュニジアディナール", nameEn: "Tunisian Dinar", iso2: "tn" },
  { code: "TOP", nameJa: "パアンガ", nameEn: "Tongan Paʻanga", iso2: "to" },
  { code: "TRY", nameJa: "トルコリラ", nameEn: "Turkish Lira", iso2: "tr" },
  { code: "TTD", nameJa: "トリニダード・トバゴドル", nameEn: "Trinidad and Tobago Dollar", iso2: "tt" },
  { code: "TWD", nameJa: "台湾ドル", nameEn: "New Taiwan Dollar", iso2: "tw" },
  { code: "TZS", nameJa: "タンザニアシリング", nameEn: "Tanzanian Shilling", iso2: "tz" },
  { code: "UAH", nameJa: "フリヴニャ", nameEn: "Ukrainian Hryvnia", iso2: "ua" },
  { code: "UGX", nameJa: "ウガンダシリング", nameEn: "Ugandan Shilling", iso2: "ug" },
  { code: "USD", nameJa: "米ドル", nameEn: "United States Dollar", iso2: "us" },
  { code: "UYU", nameJa: "ウルグアイペソ", nameEn: "Uruguayan Peso", iso2: "uy" },
  { code: "UZS", nameJa: "スム", nameEn: "Uzbekistani Soʻm", iso2: "uz" },
  { code: "VES", nameJa: "ベネズエラボリバル", nameEn: "Venezuelan Bolívar", iso2: "ve" },
  { code: "VND", nameJa: "ドン", nameEn: "Vietnamese Ðồng", iso2: "vn" },
  { code: "VUV", nameJa: "バツ", nameEn: "Vanuatu Vatu", iso2: "vu" },
  { code: "WST", nameJa: "タラ", nameEn: "Samoan Tala", iso2: "ws" },
  { code: "XAF", nameJa: "CFAフラン(中部アフリカ)", nameEn: "Central African CFA Franc", iso2: "cm" },
  { code: "XCD", nameJa: "東カリブドル", nameEn: "East Caribbean Dollar", iso2: "ag" },
  { code: "XOF", nameJa: "CFAフラン(西アフリカ)", nameEn: "West African CFA Franc", iso2: "sn" },
  { code: "XPF", nameJa: "CFPフラン", nameEn: "CFP Franc", iso2: "pf" },
  { code: "YER", nameJa: "イエメンリアル", nameEn: "Yemeni Rial", iso2: "ye" },
  { code: "ZAR", nameJa: "ランド", nameEn: "South African Rand", iso2: "za" },
  { code: "ZMW", nameJa: "クワチャ", nameEn: "Zambian Kwacha", iso2: "zm" },
  { code: "ZWL", nameJa: "ジンバブエドル", nameEn: "Zimbabwean Dollar", iso2: "zw" }
];

// コードからマスタ情報を引くためのMap
const CURRENCY_MAP = new Map(CURRENCIES.map((c) => [c.code, c]));
